INSERT INTO rma_tickets
  (rma_number, customer_name, priority, ticket_status, assigned_technician, due_date,
   general_description, accessories_received, attachments, products,
   created_by, created_date, updated_by, updated_date)
VALUES
(
  'RMA-1748000000000-2P8',
  'Gulf Tech Solutions',
  'Medium',
  'Cancelled',
  'tech1@myrma.com',
  '2026-05-21',
  'Overheating during normal use. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Remote control, Stylus pen, USB cable',
  NULL,
  '[{"product_name":"HP LaserJet Pro M404n","serial_number":"SN22ONUC9S","product_status":"Under Repair","warranty_status":"Out of Warranty","issue_description":"Charging port damaged"}]'::jsonb,
  'tech1@myrma.com',
  '2026-02-23T19:20:07.125Z'::timestamptz,
  'tech2@myrma.com',
  '2026-04-16T19:20:07.125Z'::timestamptz
),
(
  'RMA-1748000001337-NKJ',
  'Horizon IT Services',
  'Critical',
  'Cancelled',
  'tech1@myrma.com',
  '2026-05-13',
  'Overheating during normal use. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Carrying case, Stylus pen, Remote control',
  NULL,
  '[{"product_name":"Canon PIXMA MG3650","serial_number":"SNK9LUWLKD","product_status":"Pending Inspection","warranty_status":"Out of Warranty","issue_description":"Camera not functioning"}]'::jsonb,
  'bika.qds@gmail.com',
  '2026-03-03T19:20:07.125Z'::timestamptz,
  'bika.qds@gmail.com',
  '2026-03-21T19:20:07.125Z'::timestamptz
),
(
  'RMA-1748000002674-E7Z',
  'Al Sadd Industries',
  'Medium',
  'New',
  'tech1@myrma.com',
  '2026-05-20',
  'Keyboard keys not responding. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Power adapter, Stylus pen',
  NULL,
  '[{"product_name":"Asus ROG Zephyrus G14","serial_number":"SNZDEGWDCT","product_status":"Returned to Customer","warranty_status":"In Warranty","issue_description":"Device freezing randomly"},{"product_name":"Apple MacBook Pro 14","serial_number":"SNG41YM9CE","product_status":"Under Repair","warranty_status":"Out of Warranty","issue_description":"Charging port damaged"},{"product_name":"Canon PIXMA MG3650","serial_number":"SNF65I2NEK","product_status":"Returned to Customer","warranty_status":"Out of Warranty","issue_description":"Battery drains too quickly"}]'::jsonb,
  'tech2@myrma.com',
  '2026-03-02T19:20:07.125Z'::timestamptz,
  'bika.qds@gmail.com',
  '2026-04-13T19:20:07.125Z'::timestamptz
),
(
  'RMA-1748000004011-DK3',
  'Al Dafna Supplies',
  'Medium',
  'Completed',
  'tech1@myrma.com',
  '2026-05-18',
  'Fan making loud noise. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Stylus pen, Power adapter, Carrying case',
  NULL,
  '[{"product_name":"HP LaserJet Pro M404n","serial_number":"SNOFWKA0BF","product_status":"Under Repair","warranty_status":"In Warranty","issue_description":"Touchscreen unresponsive"},{"product_name":"HP LaserJet Pro M404n","serial_number":"SNAR7WD2EO","product_status":"Pending Inspection","warranty_status":"In Warranty","issue_description":"Touchscreen unresponsive"}]'::jsonb,
  'bika.qds@gmail.com',
  '2026-04-09T19:20:07.125Z'::timestamptz,
  'tech1@myrma.com',
  '2026-05-01T18:20:07.125Z'::timestamptz
),
(
  'RMA-1748000005348-7VY',
  'Qatar Digital Hub',
  'High',
  'Completed',
  'bika.qds@gmail.com',
  '2026-05-28',
  'Software crashing frequently. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  NULL,
  NULL,
  '[{"product_name":"Apple MacBook Pro 14","serial_number":"SNYRS1Y3US","product_status":"Under Repair","warranty_status":"In Warranty","issue_description":"Screen flickering intermittently"}]'::jsonb,
  'tech2@myrma.com',
  '2026-03-24T19:20:07.125Z'::timestamptz,
  'tech2@myrma.com',
  '2026-04-20T19:20:07.125Z'::timestamptz
),
(
  'RMA-1748000006685-MB5',
  'Al Sadd Industries',
  'Medium',
  'Completed',
  'tech1@myrma.com',
  '2026-05-27',
  'Hard drive not detected. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  NULL,
  NULL,
  '[{"product_name":"Apple MacBook Pro 14","serial_number":"SNVV1G0H2D","product_status":"Returned to Customer","warranty_status":"In Warranty","issue_description":"Battery drains too quickly"}]'::jsonb,
  'bika.qds@gmail.com',
  '2026-02-23T19:20:07.125Z'::timestamptz,
  'bika.qds@gmail.com',
  '2026-05-03T18:20:07.125Z'::timestamptz
),
(
  'RMA-1748000008022-AP3',
  'Al Majid Tech',
  'Medium',
  'On Hold',
  'tech1@myrma.com',
  '2026-05-20',
  'Device not powering on. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Remote control',
  NULL,
  '[{"product_name":"Apple MacBook Pro 14","serial_number":"SNT9NXB54U","product_status":"Returned to Customer","warranty_status":"Out of Warranty","issue_description":"Screen flickering intermittently"},{"product_name":"Dell XPS 15","serial_number":"SNFVHNFM0V","product_status":"Under Repair","warranty_status":"Out of Warranty","issue_description":"Camera not functioning"}]'::jsonb,
  'tech1@myrma.com',
  '2026-02-28T19:20:07.125Z'::timestamptz,
  'tech2@myrma.com',
  '2026-04-10T19:20:07.125Z'::timestamptz
),
(
  'RMA-1748000009359-AGW',
  'Horizon IT Services',
  'Medium',
  'New',
  'bika.qds@gmail.com',
  '2026-05-24',
  'Keyboard keys not responding. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Carrying case',
  NULL,
  '[{"product_name":"LG OLED 65 C3","serial_number":"SNAZPVLTU7","product_status":"Pending Inspection","warranty_status":"Out of Warranty","issue_description":"Keyboard keys not responding"}]'::jsonb,
  'tech1@myrma.com',
  '2026-04-29T18:20:07.125Z'::timestamptz,
  'tech1@myrma.com',
  '2026-05-09T18:20:07.125Z'::timestamptz
),
(
  'RMA-1748000010696-YK1',
  'Horizon IT Services',
  'Medium',
  'Completed',
  'tech2@myrma.com',
  '2026-05-26',
  'Battery drains too quickly. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  NULL,
  NULL,
  '[{"product_name":"Dell XPS 15","serial_number":"SNTY88V2ZG","product_status":"Returned to Customer","warranty_status":"In Warranty","issue_description":"Device not powering on"},{"product_name":"Lenovo ThinkPad X1 Carbon","serial_number":"SNCDBIHK5L","product_status":"Repaired","warranty_status":"Out of Warranty","issue_description":"Device freezing randomly"}]'::jsonb,
  'tech2@myrma.com',
  '2026-03-30T19:20:07.125Z'::timestamptz,
  'bika.qds@gmail.com',
  '2026-05-14T18:20:07.125Z'::timestamptz
),
(
  'RMA-1748000012033-QS4',
  'Al Dafna Supplies',
  'High',
  'Completed',
  'tech1@myrma.com',
  '2026-05-25',
  'Display showing dead pixels. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Remote control, USB cable',
  NULL,
  '[{"product_name":"Apple MacBook Pro 14","serial_number":"SN6QDE46OO","product_status":"Waiting for Parts","warranty_status":"In Warranty","issue_description":"Charging port damaged"}]'::jsonb,
  'tech2@myrma.com',
  '2026-02-26T19:20:07.125Z'::timestamptz,
  'tech1@myrma.com',
  '2026-02-27T19:20:07.125Z'::timestamptz
),
(
  'RMA-1748000013370-2OU',
  'Al Dafna Supplies',
  'Low',
  'Completed',
  'bika.qds@gmail.com',
  '2026-05-29',
  'Speaker producing distorted sound. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Remote control',
  NULL,
  '[{"product_name":"Apple MacBook Pro 14","serial_number":"SN4QE50XXH","product_status":"Waiting for Parts","warranty_status":"In Warranty","issue_description":"Hard drive not detected"},{"product_name":"Microsoft Surface Pro 9","serial_number":"SNYKBZ1BQJ","product_status":"Pending Inspection","warranty_status":"Out of Warranty","issue_description":"Device not powering on"},{"product_name":"Samsung Galaxy S24","serial_number":"SNNOM58BM4","product_status":"Under Repair","warranty_status":"In Warranty","issue_description":"Overheating during normal use"}]'::jsonb,
  'bika.qds@gmail.com',
  '2026-05-06T18:20:07.125Z'::timestamptz,
  'tech1@myrma.com',
  '2026-05-09T18:20:07.125Z'::timestamptz
),
(
  'RMA-1748000014707-IBS',
  'Al Khor Manufacturing',
  'Medium',
  'Cancelled',
  'tech2@myrma.com',
  '2026-05-26',
  'Fan making loud noise. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'USB cable, Power adapter, Remote control',
  NULL,
  '[{"product_name":"Lenovo ThinkPad X1 Carbon","serial_number":"SNOYTQ1BNH","product_status":"Pending Inspection","warranty_status":"In Warranty","issue_description":"Speaker producing distorted sound"},{"product_name":"Sony Bravia 55 OLED","serial_number":"SNG9RU11S2","product_status":"Repaired","warranty_status":"Out of Warranty","issue_description":"Screen flickering intermittently"},{"product_name":"Asus ROG Zephyrus G14","serial_number":"SN0ALQ2HY6","product_status":"Waiting for Parts","warranty_status":"Out of Warranty","issue_description":"Display showing dead pixels"}]'::jsonb,
  'tech1@myrma.com',
  '2026-03-26T19:20:07.125Z'::timestamptz,
  'bika.qds@gmail.com',
  '2026-05-17T18:20:07.125Z'::timestamptz
),
(
  'RMA-1748000016044-FEM',
  'Al Majid Tech',
  'Medium',
  'Completed',
  'tech1@myrma.com',
  '2026-05-31',
  'Device freezing randomly. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Power adapter, Carrying case, USB cable',
  NULL,
  '[{"product_name":"Dell XPS 15","serial_number":"SNQAQR768A","product_status":"Returned to Customer","warranty_status":"In Warranty","issue_description":"Keyboard keys not responding"}]'::jsonb,
  'tech2@myrma.com',
  '2026-02-25T19:20:07.125Z'::timestamptz,
  'tech2@myrma.com',
  '2026-04-24T18:20:07.125Z'::timestamptz
),
(
  'RMA-1748000017381-77G',
  'Skyline Solutions',
  'Critical',
  'New',
  'bika.qds@gmail.com',
  '2026-05-20',
  'Fan making loud noise. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  NULL,
  NULL,
  '[{"product_name":"Asus ROG Zephyrus G14","serial_number":"SNYHLACW3Z","product_status":"Under Repair","warranty_status":"Out of Warranty","issue_description":"Overheating during normal use"}]'::jsonb,
  'bika.qds@gmail.com',
  '2026-05-06T18:20:07.125Z'::timestamptz,
  'tech1@myrma.com',
  '2026-05-11T18:20:07.125Z'::timestamptz
),
(
  'RMA-1748000018718-AWT',
  'Skyline Solutions',
  'High',
  'On Hold',
  'bika.qds@gmail.com',
  '2026-05-29',
  'Display showing dead pixels. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Carrying case',
  NULL,
  '[{"product_name":"Samsung Galaxy S24","serial_number":"SNQ32OSA5H","product_status":"Under Repair","warranty_status":"Out of Warranty","issue_description":"Touchscreen unresponsive"}]'::jsonb,
  'bika.qds@gmail.com',
  '2026-05-16T18:20:07.125Z'::timestamptz,
  'tech2@myrma.com',
  '2026-05-16T18:20:07.125Z'::timestamptz
),
(
  'RMA-1748000020055-PG1',
  'Al Majid Tech',
  'Medium',
  'Cancelled',
  'tech1@myrma.com',
  '2026-05-30',
  'Speaker producing distorted sound. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Remote control, USB cable',
  NULL,
  '[{"product_name":"Asus ROG Zephyrus G14","serial_number":"SNCGJ7IONW","product_status":"Returned to Customer","warranty_status":"Out of Warranty","issue_description":"Display showing dead pixels"},{"product_name":"Canon PIXMA MG3650","serial_number":"SNE3QY2ONH","product_status":"Returned to Customer","warranty_status":"Out of Warranty","issue_description":"Software crashing frequently"},{"product_name":"Dell XPS 15","serial_number":"SN5OMP0M7B","product_status":"Repaired","warranty_status":"Out of Warranty","issue_description":"Wi-Fi connectivity issues"}]'::jsonb,
  'tech2@myrma.com',
  '2026-03-06T19:20:07.125Z'::timestamptz,
  'tech2@myrma.com',
  '2026-03-10T19:20:07.125Z'::timestamptz
),
(
  'RMA-1748000021392-REJ',
  'Gulf Tech Solutions',
  'High',
  'In Progress',
  'tech2@myrma.com',
  '2026-05-24',
  'Overheating during normal use. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  NULL,
  NULL,
  '[{"product_name":"Microsoft Surface Pro 9","serial_number":"SNM8F2SELO","product_status":"Under Repair","warranty_status":"In Warranty","issue_description":"Display showing dead pixels"},{"product_name":"HP LaserJet Pro M404n","serial_number":"SN7IE1T46R","product_status":"Repaired","warranty_status":"Out of Warranty","issue_description":"Wi-Fi connectivity issues"}]'::jsonb,
  'bika.qds@gmail.com',
  '2026-04-25T18:20:07.125Z'::timestamptz,
  'tech2@myrma.com',
  '2026-04-29T18:20:07.125Z'::timestamptz
),
(
  'RMA-1748000022729-64Y',
  'Gulf Tech Solutions',
  'High',
  'Completed',
  'tech1@myrma.com',
  '2026-05-20',
  'Screen flickering intermittently. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Power adapter, Remote control',
  NULL,
  '[{"product_name":"Canon PIXMA MG3650","serial_number":"SNOGLNUNRQ","product_status":"Under Repair","warranty_status":"In Warranty","issue_description":"Touchscreen unresponsive"},{"product_name":"Dell XPS 15","serial_number":"SNHPUF29JO","product_status":"Under Repair","warranty_status":"In Warranty","issue_description":"Touchscreen unresponsive"}]'::jsonb,
  'bika.qds@gmail.com',
  '2026-05-15T18:20:07.125Z'::timestamptz,
  'tech1@myrma.com',
  '2026-05-16T18:20:07.125Z'::timestamptz
),
(
  'RMA-1748000024066-VVU',
  'Falcon Systems LLC',
  'Medium',
  'On Hold',
  'tech2@myrma.com',
  '2026-05-19',
  'Speaker producing distorted sound. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'USB cable, Carrying case, Stylus pen',
  NULL,
  '[{"product_name":"Lenovo ThinkPad X1 Carbon","serial_number":"SNAA0AUHFO","product_status":"Returned to Customer","warranty_status":"Out of Warranty","issue_description":"Screen flickering intermittently"}]'::jsonb,
  'tech2@myrma.com',
  '2026-05-13T18:20:07.125Z'::timestamptz,
  'tech1@myrma.com',
  '2026-05-14T18:20:07.125Z'::timestamptz
),
(
  'RMA-1748000025403-AC1',
  'Al Rashid Trading Co.',
  'High',
  'Cancelled',
  'bika.qds@gmail.com',
  '2026-05-14',
  'Fan making loud noise. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Remote control, HDMI cable',
  NULL,
  '[{"product_name":"HP LaserJet Pro M404n","serial_number":"SNMEXD7TD7","product_status":"Returned to Customer","warranty_status":"Out of Warranty","issue_description":"Software crashing frequently"},{"product_name":"Dell XPS 15","serial_number":"SN18R3KJMG","product_status":"Repaired","warranty_status":"In Warranty","issue_description":"Fan making loud noise"}]'::jsonb,
  'bika.qds@gmail.com',
  '2026-03-15T19:20:07.125Z'::timestamptz,
  'tech2@myrma.com',
  '2026-04-18T19:20:07.125Z'::timestamptz
),
(
  'RMA-1748000026740-DAW',
  'Falcon Systems LLC',
  'Medium',
  'Completed',
  'tech1@myrma.com',
  '2026-05-29',
  'Charging port damaged. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  NULL,
  NULL,
  '[{"product_name":"HP LaserJet Pro M404n","serial_number":"SNOROMKZ8Y","product_status":"Repaired","warranty_status":"Out of Warranty","issue_description":"Speaker producing distorted sound"}]'::jsonb,
  'bika.qds@gmail.com',
  '2026-04-04T19:20:07.125Z'::timestamptz,
  'bika.qds@gmail.com',
  '2026-04-13T19:20:07.125Z'::timestamptz
),
(
  'RMA-1748000028077-9ST',
  'Al Sadd Industries',
  'Medium',
  'Completed',
  'tech2@myrma.com',
  '2026-05-24',
  'Overheating during normal use. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Power adapter',
  NULL,
  '[{"product_name":"HP LaserJet Pro M404n","serial_number":"SNCCUOI2U6","product_status":"Under Repair","warranty_status":"In Warranty","issue_description":"Camera not functioning"}]'::jsonb,
  'tech1@myrma.com',
  '2026-03-23T19:20:07.125Z'::timestamptz,
  'tech1@myrma.com',
  '2026-04-23T19:20:07.125Z'::timestamptz
),
(
  'RMA-1748000029414-3BG',
  'Qatar Digital Hub',
  'High',
  'In Progress',
  'tech1@myrma.com',
  '2026-05-25',
  'Speaker producing distorted sound. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Remote control, Stylus pen',
  NULL,
  '[{"product_name":"Canon PIXMA MG3650","serial_number":"SNLLTFMHJY","product_status":"Returned to Customer","warranty_status":"In Warranty","issue_description":"Charging port damaged"}]'::jsonb,
  'tech2@myrma.com',
  '2026-04-09T19:20:07.125Z'::timestamptz,
  'tech1@myrma.com',
  '2026-04-10T19:20:07.125Z'::timestamptz
),
(
  'RMA-1748000030751-REG',
  'Al Sadd Industries',
  'Low',
  'New',
  'bika.qds@gmail.com',
  '2026-05-30',
  'Device not powering on. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'USB cable',
  NULL,
  '[{"product_name":"Sony Bravia 55 OLED","serial_number":"SNMQJDKPSC","product_status":"Under Repair","warranty_status":"Out of Warranty","issue_description":"Fan making loud noise"},{"product_name":"Samsung Galaxy S24","serial_number":"SNRTH5L099","product_status":"Returned to Customer","warranty_status":"Out of Warranty","issue_description":"Device freezing randomly"}]'::jsonb,
  'tech1@myrma.com',
  '2026-02-28T19:20:07.125Z'::timestamptz,
  'tech1@myrma.com',
  '2026-03-27T19:20:07.125Z'::timestamptz
),
(
  'RMA-1748000032088-VA5',
  'Falcon Systems LLC',
  'Medium',
  'In Progress',
  'bika.qds@gmail.com',
  '2026-05-22',
  'Screen flickering intermittently. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Stylus pen, Remote control',
  NULL,
  '[{"product_name":"Apple MacBook Pro 14","serial_number":"SNA3JDREIN","product_status":"Waiting for Parts","warranty_status":"Out of Warranty","issue_description":"Hard drive not detected"},{"product_name":"Asus ROG Zephyrus G14","serial_number":"SNYSHXLPZH","product_status":"Waiting for Parts","warranty_status":"Out of Warranty","issue_description":"Overheating during normal use"}]'::jsonb,
  'tech2@myrma.com',
  '2026-04-19T19:20:07.125Z'::timestamptz,
  'bika.qds@gmail.com',
  '2026-04-19T19:20:07.125Z'::timestamptz
),
(
  'RMA-1748000033425-MCW',
  'Al Rashid Trading Co.',
  'Medium',
  'Cancelled',
  'tech1@myrma.com',
  '2026-05-20',
  'Screen flickering intermittently. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Power adapter, USB cable',
  NULL,
  '[{"product_name":"LG OLED 65 C3","serial_number":"SNY833PSTV","product_status":"Waiting for Parts","warranty_status":"In Warranty","issue_description":"Device freezing randomly"},{"product_name":"LG OLED 65 C3","serial_number":"SNTSCU1VU2","product_status":"Returned to Customer","warranty_status":"In Warranty","issue_description":"Speaker producing distorted sound"}]'::jsonb,
  'tech1@myrma.com',
  '2026-05-12T18:20:07.125Z'::timestamptz,
  'tech2@myrma.com',
  '2026-05-15T18:20:07.125Z'::timestamptz
),
(
  'RMA-1748000034762-D7W',
  'Al Sadd Industries',
  'Low',
  'In Progress',
  'tech1@myrma.com',
  '2026-05-22',
  'Touchscreen unresponsive. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Power adapter, Carrying case',
  NULL,
  '[{"product_name":"HP LaserJet Pro M404n","serial_number":"SNGIJVDYL8","product_status":"Repaired","warranty_status":"In Warranty","issue_description":"Overheating during normal use"},{"product_name":"Apple MacBook Pro 14","serial_number":"SN24MVN81Q","product_status":"Returned to Customer","warranty_status":"Out of Warranty","issue_description":"Battery drains too quickly"}]'::jsonb,
  'tech2@myrma.com',
  '2026-05-07T18:20:07.125Z'::timestamptz,
  'tech2@myrma.com',
  '2026-05-12T18:20:07.125Z'::timestamptz
),
(
  'RMA-1748000036099-B6S',
  'Qatar Digital Hub',
  'Medium',
  'In Progress',
  'bika.qds@gmail.com',
  '2026-05-22',
  'Software crashing frequently. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Power adapter, Stylus pen',
  NULL,
  '[{"product_name":"Asus ROG Zephyrus G14","serial_number":"SN5EQBE3NB","product_status":"Under Repair","warranty_status":"Out of Warranty","issue_description":"Camera not functioning"}]'::jsonb,
  'tech1@myrma.com',
  '2026-03-16T19:20:07.125Z'::timestamptz,
  'tech1@myrma.com',
  '2026-05-06T18:20:07.125Z'::timestamptz
),
(
  'RMA-1748000037436-AAY',
  'Gulf Tech Solutions',
  'Medium',
  'Cancelled',
  'bika.qds@gmail.com',
  '2026-05-26',
  'Fan making loud noise. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  NULL,
  NULL,
  '[{"product_name":"LG OLED 65 C3","serial_number":"SNA7D7XZ0X","product_status":"Under Repair","warranty_status":"In Warranty","issue_description":"Fan making loud noise"},{"product_name":"Apple MacBook Pro 14","serial_number":"SNBDHJWTYN","product_status":"Returned to Customer","warranty_status":"In Warranty","issue_description":"Speaker producing distorted sound"}]'::jsonb,
  'bika.qds@gmail.com',
  '2026-03-20T19:20:07.125Z'::timestamptz,
  'tech2@myrma.com',
  '2026-04-12T19:20:07.125Z'::timestamptz
),
(
  'RMA-1748000038773-3X7',
  'Al Rashid Trading Co.',
  'Medium',
  'In Progress',
  'tech1@myrma.com',
  '2026-05-25',
  'Camera not functioning. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Power adapter, Remote control, HDMI cable',
  NULL,
  '[{"product_name":"Lenovo ThinkPad X1 Carbon","serial_number":"SN8IYJY4BW","product_status":"Under Repair","warranty_status":"In Warranty","issue_description":"Display showing dead pixels"},{"product_name":"Asus ROG Zephyrus G14","serial_number":"SNHBH5L8LB","product_status":"Waiting for Parts","warranty_status":"Out of Warranty","issue_description":"Fan making loud noise"},{"product_name":"Lenovo ThinkPad X1 Carbon","serial_number":"SN9W9GUABC","product_status":"Pending Inspection","warranty_status":"Out of Warranty","issue_description":"Keyboard keys not responding"}]'::jsonb,
  'tech1@myrma.com',
  '2026-03-04T19:20:07.125Z'::timestamptz,
  'bika.qds@gmail.com',
  '2026-05-03T18:20:07.125Z'::timestamptz
),
(
  'RMA-1748000040110-181',
  'Al Majid Tech',
  'Medium',
  'On Hold',
  'tech2@myrma.com',
  '2026-05-27',
  'Device freezing randomly. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Remote control',
  NULL,
  '[{"product_name":"Asus ROG Zephyrus G14","serial_number":"SNWJCN7SP1","product_status":"Under Repair","warranty_status":"In Warranty","issue_description":"Overheating during normal use"}]'::jsonb,
  'tech2@myrma.com',
  '2026-02-24T19:20:07.125Z'::timestamptz,
  'bika.qds@gmail.com',
  '2026-04-21T19:20:07.125Z'::timestamptz
),
(
  'RMA-1748000041447-PBD',
  'Pearl City Computers',
  'Medium',
  'Cancelled',
  'tech1@myrma.com',
  '2026-05-17',
  'Device not powering on. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  NULL,
  NULL,
  '[{"product_name":"HP LaserJet Pro M404n","serial_number":"SND0VTPDRR","product_status":"Returned to Customer","warranty_status":"In Warranty","issue_description":"Device freezing randomly"},{"product_name":"Canon PIXMA MG3650","serial_number":"SN58O19RTI","product_status":"Under Repair","warranty_status":"In Warranty","issue_description":"Device freezing randomly"}]'::jsonb,
  'tech1@myrma.com',
  '2026-04-25T18:20:07.125Z'::timestamptz,
  'tech1@myrma.com',
  '2026-05-12T18:20:07.125Z'::timestamptz
),
(
  'RMA-1748000042784-5PL',
  'Pearl City Computers',
  'Critical',
  'Completed',
  'tech1@myrma.com',
  '2026-05-21',
  'Hard drive not detected. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Remote control',
  NULL,
  '[{"product_name":"Asus ROG Zephyrus G14","serial_number":"SN4R0443EB","product_status":"Waiting for Parts","warranty_status":"In Warranty","issue_description":"Speaker producing distorted sound"},{"product_name":"Lenovo ThinkPad X1 Carbon","serial_number":"SNAKJJHM4B","product_status":"Repaired","warranty_status":"Out of Warranty","issue_description":"Device freezing randomly"}]'::jsonb,
  'bika.qds@gmail.com',
  '2026-02-27T19:20:07.125Z'::timestamptz,
  'bika.qds@gmail.com',
  '2026-02-27T19:20:07.125Z'::timestamptz
),
(
  'RMA-1748000044121-K8C',
  'Horizon IT Services',
  'Low',
  'On Hold',
  'bika.qds@gmail.com',
  '2026-05-19',
  'Battery drains too quickly. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Power adapter',
  NULL,
  '[{"product_name":"Sony Bravia 55 OLED","serial_number":"SNDWOWP9QQ","product_status":"Waiting for Parts","warranty_status":"In Warranty","issue_description":"Charging port damaged"}]'::jsonb,
  'tech2@myrma.com',
  '2026-04-20T19:20:07.125Z'::timestamptz,
  'bika.qds@gmail.com',
  '2026-05-01T18:20:07.125Z'::timestamptz
),
(
  'RMA-1748000045458-OFN',
  'Desert Rose Retail',
  'Low',
  'New',
  'bika.qds@gmail.com',
  '2026-05-20',
  'Device freezing randomly. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Carrying case, USB cable',
  NULL,
  '[{"product_name":"Asus ROG Zephyrus G14","serial_number":"SNS34DFFOQ","product_status":"Pending Inspection","warranty_status":"In Warranty","issue_description":"Battery drains too quickly"}]'::jsonb,
  'tech2@myrma.com',
  '2026-04-10T19:20:07.125Z'::timestamptz,
  'bika.qds@gmail.com',
  '2026-04-18T19:20:07.125Z'::timestamptz
),
(
  'RMA-1748000046795-OAG',
  'Desert Rose Retail',
  'Low',
  'Completed',
  'tech1@myrma.com',
  '2026-05-20',
  'Hard drive not detected. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'HDMI cable',
  NULL,
  '[{"product_name":"Apple MacBook Pro 14","serial_number":"SN4G6V1LKE","product_status":"Repaired","warranty_status":"In Warranty","issue_description":"Screen flickering intermittently"},{"product_name":"LG OLED 65 C3","serial_number":"SNHOVIO8M2","product_status":"Repaired","warranty_status":"In Warranty","issue_description":"Display showing dead pixels"}]'::jsonb,
  'tech2@myrma.com',
  '2026-05-14T18:20:07.125Z'::timestamptz,
  'bika.qds@gmail.com',
  '2026-05-17T18:20:07.125Z'::timestamptz
),
(
  'RMA-1748000048132-H47',
  'Al Noor Electronics',
  'Critical',
  'Completed',
  'tech1@myrma.com',
  '2026-05-19',
  'Overheating during normal use. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  NULL,
  NULL,
  '[{"product_name":"Apple MacBook Pro 14","serial_number":"SNCQ9V27AN","product_status":"Waiting for Parts","warranty_status":"Out of Warranty","issue_description":"Software crashing frequently"},{"product_name":"Sony Bravia 55 OLED","serial_number":"SN1C6STYWJ","product_status":"Waiting for Parts","warranty_status":"Out of Warranty","issue_description":"Charging port damaged"},{"product_name":"Lenovo ThinkPad X1 Carbon","serial_number":"SN2OI4VKM1","product_status":"Pending Inspection","warranty_status":"In Warranty","issue_description":"Display showing dead pixels"}]'::jsonb,
  'tech1@myrma.com',
  '2026-04-19T19:20:07.125Z'::timestamptz,
  'tech1@myrma.com',
  '2026-04-24T18:20:07.125Z'::timestamptz
),
(
  'RMA-1748000049469-GDI',
  'Al Dafna Supplies',
  'Low',
  'New',
  'tech2@myrma.com',
  '2026-05-18',
  'Speaker producing distorted sound. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  NULL,
  NULL,
  '[{"product_name":"Microsoft Surface Pro 9","serial_number":"SNX7MWYEJF","product_status":"Repaired","warranty_status":"Out of Warranty","issue_description":"Touchscreen unresponsive"},{"product_name":"Microsoft Surface Pro 9","serial_number":"SN27F2BH6S","product_status":"Pending Inspection","warranty_status":"In Warranty","issue_description":"Device freezing randomly"}]'::jsonb,
  'bika.qds@gmail.com',
  '2026-03-04T19:20:07.125Z'::timestamptz,
  'bika.qds@gmail.com',
  '2026-03-17T19:20:07.125Z'::timestamptz
),
(
  'RMA-1748000050806-UET',
  'Al Fardan Group',
  'Medium',
  'New',
  'tech2@myrma.com',
  '2026-05-15',
  'Device freezing randomly. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Power adapter, Carrying case',
  NULL,
  '[{"product_name":"LG OLED 65 C3","serial_number":"SNCOPRLBCI","product_status":"Under Repair","warranty_status":"In Warranty","issue_description":"Fan making loud noise"}]'::jsonb,
  'tech1@myrma.com',
  '2026-04-05T19:20:07.125Z'::timestamptz,
  'tech2@myrma.com',
  '2026-04-07T19:20:07.125Z'::timestamptz
),
(
  'RMA-1748000052143-P3W',
  'Al Majid Tech',
  'Low',
  'On Hold',
  'tech2@myrma.com',
  '2026-05-15',
  'Battery drains too quickly. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  NULL,
  NULL,
  '[{"product_name":"Sony Bravia 55 OLED","serial_number":"SNU44OT4SR","product_status":"Repaired","warranty_status":"In Warranty","issue_description":"Device freezing randomly"}]'::jsonb,
  'tech1@myrma.com',
  '2026-05-06T18:20:07.125Z'::timestamptz,
  'tech2@myrma.com',
  '2026-05-11T18:20:07.125Z'::timestamptz
),
(
  'RMA-1748000053480-E10',
  'Al Wakra Enterprises',
  'Low',
  'Completed',
  'bika.qds@gmail.com',
  '2026-05-26',
  'Wi-Fi connectivity issues. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Carrying case',
  NULL,
  '[{"product_name":"LG OLED 65 C3","serial_number":"SNUIL289YQ","product_status":"Returned to Customer","warranty_status":"In Warranty","issue_description":"Device freezing randomly"},{"product_name":"Lenovo ThinkPad X1 Carbon","serial_number":"SND06JZZWO","product_status":"Pending Inspection","warranty_status":"In Warranty","issue_description":"Touchscreen unresponsive"},{"product_name":"Canon PIXMA MG3650","serial_number":"SNLOBN7Y84","product_status":"Under Repair","warranty_status":"In Warranty","issue_description":"Device freezing randomly"}]'::jsonb,
  'tech1@myrma.com',
  '2026-04-08T19:20:07.125Z'::timestamptz,
  'tech1@myrma.com',
  '2026-05-09T18:20:07.125Z'::timestamptz
),
(
  'RMA-1748000054817-0TY',
  'Al Majid Tech',
  'Medium',
  'Completed',
  'tech2@myrma.com',
  '2026-05-30',
  'Keyboard keys not responding. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Power adapter, USB cable',
  NULL,
  '[{"product_name":"Sony Bravia 55 OLED","serial_number":"SNOJ6BW5TE","product_status":"Pending Inspection","warranty_status":"Out of Warranty","issue_description":"Wi-Fi connectivity issues"},{"product_name":"LG OLED 65 C3","serial_number":"SN5UUFQ7OK","product_status":"Repaired","warranty_status":"In Warranty","issue_description":"Device freezing randomly"}]'::jsonb,
  'tech2@myrma.com',
  '2026-05-16T18:20:07.125Z'::timestamptz,
  'tech2@myrma.com',
  '2026-05-16T18:20:07.125Z'::timestamptz
),
(
  'RMA-1748000056154-FYM',
  'Al Khor Manufacturing',
  'Low',
  'Completed',
  'tech2@myrma.com',
  '2026-05-30',
  'Charging port damaged. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'USB cable, Power adapter',
  NULL,
  '[{"product_name":"Dell XPS 15","serial_number":"SNGXNRDPL0","product_status":"Repaired","warranty_status":"Out of Warranty","issue_description":"Charging port damaged"}]'::jsonb,
  'tech2@myrma.com',
  '2026-02-16T19:20:07.125Z'::timestamptz,
  'bika.qds@gmail.com',
  '2026-04-15T19:20:07.126Z'::timestamptz
),
(
  'RMA-1748000057491-PBC',
  'Al Fardan Group',
  'Medium',
  'New',
  'tech2@myrma.com',
  '2026-05-24',
  'Software crashing frequently. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Remote control',
  NULL,
  '[{"product_name":"Canon PIXMA MG3650","serial_number":"SN1EFAD5UE","product_status":"Waiting for Parts","warranty_status":"In Warranty","issue_description":"Battery drains too quickly"},{"product_name":"Microsoft Surface Pro 9","serial_number":"SN82KIPMCX","product_status":"Returned to Customer","warranty_status":"In Warranty","issue_description":"Display showing dead pixels"},{"product_name":"Canon PIXMA MG3650","serial_number":"SNFM26NEKL","product_status":"Under Repair","warranty_status":"In Warranty","issue_description":"Keyboard keys not responding"}]'::jsonb,
  'bika.qds@gmail.com',
  '2026-05-05T18:20:07.126Z'::timestamptz,
  'tech1@myrma.com',
  '2026-05-10T18:20:07.126Z'::timestamptz
),
(
  'RMA-1748000058828-O77',
  'Skyline Solutions',
  'Medium',
  'New',
  'tech2@myrma.com',
  '2026-05-26',
  'Screen flickering intermittently. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Remote control',
  NULL,
  '[{"product_name":"LG OLED 65 C3","serial_number":"SN1RWC8O1X","product_status":"Returned to Customer","warranty_status":"In Warranty","issue_description":"Device freezing randomly"},{"product_name":"Samsung Galaxy S24","serial_number":"SNKZXAUD6H","product_status":"Under Repair","warranty_status":"Out of Warranty","issue_description":"Device not powering on"},{"product_name":"HP LaserJet Pro M404n","serial_number":"SNVC3FGYH3","product_status":"Pending Inspection","warranty_status":"In Warranty","issue_description":"Device not powering on"}]'::jsonb,
  'bika.qds@gmail.com',
  '2026-04-12T19:20:07.126Z'::timestamptz,
  'bika.qds@gmail.com',
  '2026-05-03T18:20:07.126Z'::timestamptz
),
(
  'RMA-1748000060165-NM3',
  'Desert Rose Retail',
  'Medium',
  'Completed',
  'tech1@myrma.com',
  '2026-05-30',
  'Fan making loud noise. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  NULL,
  NULL,
  '[{"product_name":"Sony Bravia 55 OLED","serial_number":"SNPHORKECL","product_status":"Under Repair","warranty_status":"In Warranty","issue_description":"Screen flickering intermittently"}]'::jsonb,
  'tech1@myrma.com',
  '2026-03-15T19:20:07.126Z'::timestamptz,
  'tech2@myrma.com',
  '2026-04-29T18:20:07.126Z'::timestamptz
),
(
  'RMA-1748000061502-IWJ',
  'Al Sadd Industries',
  'High',
  'On Hold',
  'bika.qds@gmail.com',
  '2026-05-27',
  'Hard drive not detected. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  NULL,
  NULL,
  '[{"product_name":"Canon PIXMA MG3650","serial_number":"SNRJ0ODNIW","product_status":"Returned to Customer","warranty_status":"In Warranty","issue_description":"Charging port damaged"},{"product_name":"LG OLED 65 C3","serial_number":"SN21AM7846","product_status":"Pending Inspection","warranty_status":"Out of Warranty","issue_description":"Overheating during normal use"}]'::jsonb,
  'tech2@myrma.com',
  '2026-03-16T19:20:07.126Z'::timestamptz,
  'tech2@myrma.com',
  '2026-03-25T19:20:07.126Z'::timestamptz
),
(
  'RMA-1748000062839-JDD',
  'Al Fardan Group',
  'High',
  'In Progress',
  'bika.qds@gmail.com',
  '2026-05-16',
  'Device freezing randomly. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Carrying case, Power adapter, HDMI cable',
  NULL,
  '[{"product_name":"Apple MacBook Pro 14","serial_number":"SNXJNWJKJB","product_status":"Under Repair","warranty_status":"Out of Warranty","issue_description":"Display showing dead pixels"},{"product_name":"Apple MacBook Pro 14","serial_number":"SNEF2B408O","product_status":"Under Repair","warranty_status":"Out of Warranty","issue_description":"Fan making loud noise"}]'::jsonb,
  'tech2@myrma.com',
  '2026-03-26T19:20:07.126Z'::timestamptz,
  'tech1@myrma.com',
  '2026-04-14T19:20:07.126Z'::timestamptz
),
(
  'RMA-1748000064176-XRH',
  'Al Khor Manufacturing',
  'Low',
  'In Progress',
  'tech1@myrma.com',
  '2026-05-31',
  'Screen flickering intermittently. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Stylus pen, HDMI cable, Remote control',
  NULL,
  '[{"product_name":"Canon PIXMA MG3650","serial_number":"SN1HPJ2TPT","product_status":"Repaired","warranty_status":"In Warranty","issue_description":"Device freezing randomly"},{"product_name":"LG OLED 65 C3","serial_number":"SNABA80344","product_status":"Pending Inspection","warranty_status":"Out of Warranty","issue_description":"Touchscreen unresponsive"}]'::jsonb,
  'tech2@myrma.com',
  '2026-04-01T19:20:07.126Z'::timestamptz,
  'tech2@myrma.com',
  '2026-04-29T18:20:07.126Z'::timestamptz
),
(
  'RMA-1748000065513-843',
  'Qatar Digital Hub',
  'High',
  'In Progress',
  'bika.qds@gmail.com',
  '2026-05-24',
  'Battery drains too quickly. Customer reported the issue on multiple occasions. Unit has been received and is pending service review.',
  'Stylus pen',
  NULL,
  '[{"product_name":"Dell XPS 15","serial_number":"SNUYCC8BSW","product_status":"Waiting for Parts","warranty_status":"Out of Warranty","issue_description":"Device not powering on"}]'::jsonb,
  'bika.qds@gmail.com',
  '2026-04-09T19:20:07.126Z'::timestamptz,
  'tech1@myrma.com',
  '2026-04-29T18:20:07.126Z'::timestamptz
);