export function validatePasswordStrength(pw) {
  if (!pw || pw.length < 8) return 'Password must be at least 8 characters'
  if (!/[A-Z]/.test(pw)) return 'Password must contain an uppercase letter'
  if (!/[a-z]/.test(pw)) return 'Password must contain a lowercase letter'
  if (!/[0-9]/.test(pw)) return 'Password must contain a number'
  return null
}

export function getDefaultPermissions() {
  return {
    products: {
      view: false,
      create: false,
      edit: false,
      delete: false,
      export: false,
      import: false,
    },
    customers: {
      view: false,
      create: false,
      edit: false,
      delete: false,
      export: false,
      import: false,
      view_history: false,
    },
    rma_tickets: {
      view_all: false,
      view_assigned: false,
      create: false,
      edit_all: false,
      edit_assigned: false,
      delete: false,
      assign: false,
      change_status: false,
      change_priority: false,
      add_comments: false,
      delete_comments: false,
      view_activity: false,
      attach_files: false,
      delete_files: false,
      print_labels: false,
      export: false,
    },
    inventory: {
      view: false,
      resolve_units: false,
      manage_batches: false,
      delete: false,
      export: false,
      manage_warehouses: false,
      transfer: false,
    },
    dashboard: {
      view_dashboard: false,
      view_analytics: false,
      view_reports: false,
      export_reports: false,
      customize_dashboard: false,
    },
    user_management: {
      view_users: false,
      create_users: false,
      edit_users: false,
      delete_users: false,
      assign_roles: false,
      manage_permissions: false,
      create_roles: false,
      delete_roles: false,
    },
    settings: {
      view_settings: false,
      edit_company_info: false,
      edit_branding: false,
      manage_email_templates: false,
      manage_statuses: false,
      manage_priorities: false,
      manage_categories: false,
      view_audit_logs: false,
    },
  }
}

export function getRoleTemplates() {
  return [
    {
      key: 'super_admin',
      name: 'Super Admin',
      icon: '👑',
      description: 'Full system access including user management and system settings',
      permissions: {
        products: {
          view: true,
          create: true,
          edit: true,
          delete: true,
          export: true,
          import: true,
        },
        customers: {
          view: true,
          create: true,
          edit: true,
          delete: true,
          export: true,
          import: true,
          view_history: true,
        },
        rma_tickets: {
          view_all: true,
          view_assigned: true,
          create: true,
          edit_all: true,
          edit_assigned: true,
          delete: true,
          assign: true,
          change_status: true,
          change_priority: true,
          add_comments: true,
          delete_comments: true,
          view_activity: true,
          attach_files: true,
          delete_files: true,
          print_labels: true,
          export: true,
        },
        inventory: {
          view: true,
          resolve_units: true,
          manage_batches: true,
          delete: true,
          export: true,
          manage_warehouses: true,
          transfer: true,
        },
        dashboard: {
          view_dashboard: true,
          view_analytics: true,
          view_reports: true,
          export_reports: true,
          customize_dashboard: true,
        },
        user_management: {
          view_users: true,
          create_users: true,
          edit_users: true,
          delete_users: true,
          assign_roles: true,
          manage_permissions: true,
          create_roles: true,
          delete_roles: true,
        },
        settings: {
          view_settings: true,
          edit_company_info: true,
          edit_branding: true,
          manage_email_templates: true,
          manage_statuses: true,
          manage_priorities: true,
          manage_categories: true,
          view_audit_logs: true,
        },
      },
    },
    {
      key: 'admin',
      name: 'Admin',
      icon: '👑',
      description: 'Management access without user permission controls',
      permissions: {
        products: {
          view: true,
          create: true,
          edit: true,
          delete: true,
          export: true,
          import: true,
        },
        customers: {
          view: true,
          create: true,
          edit: true,
          delete: true,
          export: true,
          import: true,
          view_history: true,
        },
        rma_tickets: {
          view_all: true,
          view_assigned: true,
          create: true,
          edit_all: true,
          edit_assigned: true,
          delete: false,
          assign: true,
          change_status: true,
          change_priority: true,
          add_comments: true,
          delete_comments: false,
          view_activity: true,
          attach_files: true,
          delete_files: false,
          print_labels: true,
          export: true,
        },
        inventory: {
          view: true,
          resolve_units: true,
          manage_batches: true,
          delete: false,
          export: true,
          manage_warehouses: true,
          transfer: true,
        },
        dashboard: {
          view_dashboard: true,
          view_analytics: true,
          view_reports: true,
          export_reports: true,
          customize_dashboard: true,
        },
        user_management: {
          view_users: true,
          create_users: true,
          edit_users: true,
          delete_users: false,
          assign_roles: true,
          manage_permissions: false,
          create_roles: false,
          delete_roles: false,
        },
        settings: {
          view_settings: true,
          edit_company_info: true,
          edit_branding: true,
          manage_email_templates: true,
          manage_statuses: true,
          manage_priorities: true,
          manage_categories: true,
          view_audit_logs: true,
        },
      },
    },
    {
      key: 'manager',
      name: 'Manager',
      icon: '👔',
      description: 'Team lead with full operational access but limited system settings',
      permissions: {
        products: {
          view: true,
          create: true,
          edit: true,
          delete: false,
          export: true,
          import: true,
        },
        customers: {
          view: true,
          create: true,
          edit: true,
          delete: false,
          export: true,
          import: true,
          view_history: true,
        },
        rma_tickets: {
          view_all: true,
          view_assigned: true,
          create: true,
          edit_all: true,
          edit_assigned: true,
          delete: false,
          assign: true,
          change_status: true,
          change_priority: true,
          add_comments: true,
          delete_comments: false,
          view_activity: true,
          attach_files: true,
          delete_files: false,
          print_labels: true,
          export: true,
        },
        inventory: {
          view: true,
          resolve_units: true,
          manage_batches: true,
          delete: false,
          export: true,
          manage_warehouses: false,
          transfer: true,
        },
        dashboard: {
          view_dashboard: true,
          view_analytics: true,
          view_reports: true,
          export_reports: true,
          customize_dashboard: true,
        },
        user_management: {
          view_users: true,
          create_users: false,
          edit_users: false,
          delete_users: false,
          assign_roles: false,
          manage_permissions: false,
          create_roles: false,
          delete_roles: false,
        },
        settings: {
          view_settings: true,
          edit_company_info: false,
          edit_branding: false,
          manage_email_templates: false,
          manage_statuses: true,
          manage_priorities: true,
          manage_categories: true,
          view_audit_logs: true,
        },
      },
    },
    {
      key: 'technician',
      name: 'Technician',
      icon: '🔧',
      description: 'Field worker with limited editing rights',
      permissions: {
        products: {
          view: true,
          create: false,
          edit: false,
          delete: false,
          export: false,
          import: false,
        },
        customers: {
          view: true,
          create: false,
          edit: false,
          delete: false,
          export: false,
          import: false,
          view_history: true,
        },
        rma_tickets: {
          view_all: true,
          view_assigned: true,
          create: false,
          edit_all: false,
          edit_assigned: true,
          delete: false,
          assign: false,
          change_status: true,
          change_priority: false,
          add_comments: true,
          delete_comments: false,
          view_activity: true,
          attach_files: true,
          delete_files: false,
          print_labels: true,
          export: false,
        },
        inventory: {
          view: true,
          resolve_units: true,
          manage_batches: false,
          delete: false,
          export: false,
          manage_warehouses: false,
          transfer: false,
        },
        dashboard: {
          view_dashboard: true,
          view_analytics: false,
          view_reports: false,
          export_reports: false,
          customize_dashboard: false,
        },
        user_management: {
          view_users: false,
          create_users: false,
          edit_users: false,
          delete_users: false,
          assign_roles: false,
          manage_permissions: false,
          create_roles: false,
          delete_roles: false,
        },
        settings: {
          view_settings: false,
          edit_company_info: false,
          edit_branding: false,
          manage_email_templates: false,
          manage_statuses: false,
          manage_priorities: false,
          manage_categories: false,
          view_audit_logs: false,
        },
      },
    },
    {
      key: 'viewer',
      name: 'Viewer',
      icon: '👁️',
      description: 'Read-only access to all data',
      permissions: {
        products: {
          view: true,
          create: false,
          edit: false,
          delete: false,
          export: false,
          import: false,
        },
        customers: {
          view: true,
          create: false,
          edit: false,
          delete: false,
          export: false,
          import: false,
          view_history: true,
        },
        rma_tickets: {
          view_all: true,
          view_assigned: false,
          create: false,
          edit_all: false,
          edit_assigned: false,
          delete: false,
          assign: false,
          change_status: false,
          change_priority: false,
          add_comments: false,
          delete_comments: false,
          view_activity: true,
          attach_files: false,
          delete_files: false,
          print_labels: false,
          export: false,
        },
        inventory: {
          view: true,
          resolve_units: false,
          manage_batches: false,
          delete: false,
          export: true,
          manage_warehouses: false,
          transfer: false,
        },
        dashboard: {
          view_dashboard: true,
          view_analytics: false,
          view_reports: false,
          export_reports: false,
          customize_dashboard: false,
        },
        user_management: {
          view_users: false,
          create_users: false,
          edit_users: false,
          delete_users: false,
          assign_roles: false,
          manage_permissions: false,
          create_roles: false,
          delete_roles: false,
        },
        settings: {
          view_settings: false,
          edit_company_info: false,
          edit_branding: false,
          manage_email_templates: false,
          manage_statuses: false,
          manage_priorities: false,
          manage_categories: false,
          view_audit_logs: false,
        },
      },
    },
  ]
}
